---
abstract: 'Trigger a callback subroutine on each row of an Excel spreadsheet'
author:
  - 'Xavier Caron <xav@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-XlateExcel
no_index:
  directory:
    - t
    - inc
requires:
  Carp::Assert::More: 1.12
  Spreadsheet::ParseExcel: 0.58
  Test::Differences: 0.5
  Test::More: 0.94
version: 0.02_02
